export const TEAMS = [
  {
    id: '1',
    name: 'Chicago Bulls',
    color: '#CE1141',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Chicago_Bulls_logo.svg/1200px-Chicago_Bulls_logo.svg.png',
    players: [
      { id: 'p1', name: 'Michael Jordan' },
      { id: 'p2', name: 'Scottie Pippen' },
      { id: 'p3', name: 'Dennis Rodman' },
      { id: 'p4', name: 'Toni Kukoč' },
      { id: 'p5', name: 'Steve Kerr' },
    ],
  },
  {
    id: '2',
    name: 'L.A. Lakers',
    color: '#552583',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Los_Angeles_Lakers_logo.svg/2560px-Los_Angeles_Lakers_logo.svg.png',
    players: [
      { id: 'p6', name: 'Magic Johnson' },
      { id: 'p7', name: 'Kareem Abdul-Jabbar' },
      { id: 'p8', name: 'James Worthy' },
      { id: 'p9', name: 'Shaquille O\'Neal' },
      { id: 'p10', name: 'Kobe Bryant' },
    ],
  },
  {
    id: '3',
    name: 'Boston Celtics',
    color: '#007A33',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Boston_Celtics.svg/1200px-Boston_Celtics.svg.png',
    players: [
      { id: 'p11', name: 'Larry Bird' },
      { id: 'p12', name: 'Kevin McHale' },
      { id: 'p13', name: 'Robert Parish' },
      { id: 'p14', name: 'Bill Russell' },
      { id: 'p15', name: 'Paul Pierce' },
    ],
  },
  {
    id: '4',
    name: 'Golden St. Warriors',
    color: '#1D428A',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/01/Golden_State_Warriors_logo.svg/1200px-Golden_State_Warriors_logo.svg.png',
    players: [
      { id: 'p16', name: 'Steph Curry' },
      { id: 'p17', name: 'Klay Thompson' },
      { id: 'p18', name: 'Draymond Green' },
      { id: 'p19', name: 'Chris Mullin' },
      { id: 'p20', name: 'Kevin Durant' },
    ],
  },
  {
    id: '5',
    name: 'Miami Heat',
    color: '#98002E',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Miami_Heat_logo.svg/1200px-Miami_Heat_logo.svg.png',
    players: [
      { id: 'p21', name: 'Dwyane Wade' },
      { id: 'p22', name: 'LeBron James' },
      { id: 'p23', name: 'Chris Bosh' },
      { id: 'p24', name: 'Alonzo Mourning' },
      { id: 'p25', name: 'Tim Hardaway' },
    ],
  },
  {
    id: '6',
    name: 'San Antonio Spurs',
    color: '#000000',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/San_Antonio_Spurs.svg/1200px-San_Antonio_Spurs.svg.png',
    players: [
      { id: 'p26', name: 'Tim Duncan' },
      { id: 'p27', name: 'Tony Parker' },
      { id: 'p28', name: 'Manu Ginóbili' },
      { id: 'p29', name: 'David Robinson' },
      { id: 'p30', name: 'Kawhi Leonard' },
    ],
  },
];